version: '3'

services:
  web:
    container_name: ${PROJECT_NAME}-django
    image: ${REPO_OWNER}/${IMG_NAME}:latest
    command: gunicorn ${PROJECT_NAME}.wsgi:application --reload --bind 0.0.0.0:${PORT}
    volumes:
      - ./:/usr/src/app/
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    networks:
      - backend_network
    # ports:
    #     - ${PORT_COMPOSE}:8000
  nginx:
    container_name: ${PROJECT_NAME}-nginx
    image: nginx:1.17.2-alpine
    ports:
      - "8080:80"
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - proxypass
      - backend_network

volumes:
  static_volume:
  media_volume:

networks:
  proxypass:
  backend_network: